namespace BejeweledLivePlus
{
	public enum UREPLAYMATCHFLAG
	{
		UREPLAYMATCHFLAG_FROMUPDATESWAPPING = 1,
		UREPLAYMATCHFLAG_JUSTSWAPPED = 2,
		UREPLAYMATCHFLAG_BULGING = 4,
		UREPLAYMATCHFLAG_FIRING_STARGEM = 8
	}
}
